Mon Jan 20 09:07:48 PM CET 2025
worker-6
/home/wiss/zhang/anaconda3/envs/openeqa/bin/python
Running on MASTER_NODE=worker-6, MASTER_PORT=8885, RDZV_ID=13990
found 1,636 questions
Loading checkpoint shards:   0%|          | 0/15 [00:00<?, ?it/s]Loading checkpoint shards:   7%|▋         | 1/15 [00:19<04:39, 19.95s/it]Loading checkpoint shards:  13%|█▎        | 2/15 [00:39<04:12, 19.46s/it]Loading checkpoint shards:  20%|██        | 3/15 [01:00<04:05, 20.46s/it]Loading checkpoint shards:  27%|██▋       | 4/15 [01:16<03:22, 18.45s/it]Loading checkpoint shards:  33%|███▎      | 5/15 [01:25<02:30, 15.10s/it]Loading checkpoint shards:  40%|████      | 6/15 [01:34<01:57, 13.09s/it]Loading checkpoint shards:  47%|████▋     | 7/15 [01:43<01:34, 11.78s/it]Loading checkpoint shards:  53%|█████▎    | 8/15 [01:52<01:16, 10.91s/it]Loading checkpoint shards:  60%|██████    | 9/15 [02:01<01:01, 10.28s/it]Loading checkpoint shards:  67%|██████▋   | 10/15 [02:09<00:47,  9.47s/it]Loading checkpoint shards:  73%|███████▎  | 11/15 [02:14<00:33,  8.33s/it]Loading checkpoint shards:  80%|████████  | 12/15 [02:21<00:23,  7.75s/it]Loading checkpoint shards:  87%|████████▋ | 13/15 [02:27<00:14,  7.30s/it]Loading checkpoint shards:  93%|█████████▎| 14/15 [02:33<00:06,  6.89s/it]Loading checkpoint shards: 100%|██████████| 15/15 [02:33<00:00,  4.93s/it]Loading checkpoint shards: 100%|██████████| 15/15 [02:33<00:00, 10.26s/it]
WARNING:root:Some parameters are on the meta device device because they were offloaded to the cpu.
  0%|          | 0/1636 [00:00<?, ?it/s]Processing question_id: f2e82760-5c3c-41b1-88b6-85921b9e7b32
Question: What is the white object on the wall above the TV?
Output path: data/results/open-eqa-v0-llama-2-70b-hf-4321.json
  0%|          | 0/1636 [00:18<?, ?it/s]
Traceback (most recent call last):
  File "/home/wiss/zhang/code/open-eqa/openeqa/baselines/llama.py", line 159, in <module>
    main(parse_args())
  File "/home/wiss/zhang/code/open-eqa/openeqa/baselines/llama.py", line 147, in main
    answer = ask_question(model=model, question=question)
  File "/home/wiss/zhang/code/open-eqa/openeqa/baselines/llama.py", line 107, in ask_question
    output = model(input, max_new_tokens=max_tokens, temperature=temperature)
  File "/home/wiss/zhang/code/open-eqa/openeqa/utils/llama_utils.py", line 57, in __call__
    outputs = self.model.generate(
  File "/home/wiss/zhang/anaconda3/envs/openeqa/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/wiss/zhang/anaconda3/envs/openeqa/lib/python3.9/site-packages/transformers/generation/utils.py", line 1575, in generate
    result = self._sample(
  File "/home/wiss/zhang/anaconda3/envs/openeqa/lib/python3.9/site-packages/transformers/generation/utils.py", line 2735, in _sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
[2025-01-20 21:12:11,081] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 1497610) of binary: /home/wiss/zhang/anaconda3/envs/openeqa/bin/python
Traceback (most recent call last):
  File "/home/wiss/zhang/anaconda3/envs/openeqa/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wiss/zhang/anaconda3/envs/openeqa/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/wiss/zhang/anaconda3/envs/openeqa/lib/python3.9/site-packages/torch/distributed/run.py", line 816, in <module>
    main()
  File "/home/wiss/zhang/anaconda3/envs/openeqa/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/wiss/zhang/anaconda3/envs/openeqa/lib/python3.9/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/home/wiss/zhang/anaconda3/envs/openeqa/lib/python3.9/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/wiss/zhang/anaconda3/envs/openeqa/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/wiss/zhang/anaconda3/envs/openeqa/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/wiss/zhang/code/open-eqa/openeqa/baselines/llama.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-01-20_21:12:11
  host      : worker-6
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1497610)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
