### Starting TaskPrologue of job 2333500 on a1622 at Mon Jan 27 05:40:46 CET 2025
Running on cores 96-111 with governor ondemand
Mon Jan 27 05:40:46 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.57.01              Driver Version: 565.57.01      CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A40                     On  |   00000000:C1:00.0 Off |                  Off |
|  0%   47C    P8             23W /  300W |       1MiB /  49140MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
### Finished TaskPrologue

Mon Jan 27 05:40:50 CET 2025
a1622.nhr.fau.de
/home/hpc/v100dd/v100dd12/anaconda3/envs/openeqa/bin/python
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
found 1,636 questions
found 1,636 questions
found 1,636 results
found 1,636 results
found 1,636 questions
found 1,636 results
  0%|          | 0/1636 [00:00<?, ?it/s]  0%|          | 0/1636 [00:00<?, ?it/s]  0%|          | 0/1636 [00:00<?, ?it/s]Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/hpc/v100dd/v100dd12/code/open-eqa/openeqa/evaluation/llm_match.py", line 48, in get_llm_match_score
    set_openai_key(key=openai_key)
  File "/home/hpc/v100dd/v100dd12/code/open-eqa/openeqa/utils/openai_utils.py", line 17, in set_openai_key
    assert "OPENAI_API_KEY" in os.environ
  File "/home/hpc/v100dd/v100dd12/code/open-eqa/openeqa/evaluation/llm_match.py", line 48, in get_llm_match_score
    set_openai_key(key=openai_key)
  File "/home/hpc/v100dd/v100dd12/code/open-eqa/openeqa/utils/openai_utils.py", line 17, in set_openai_key
    assert "OPENAI_API_KEY" in os.environ
AssertionError
AssertionError
  0%|          | 0/1636 [00:00<?, ?it/s]
  0%|          | 0/1636 [00:00<?, ?it/s]
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/hpc/v100dd/v100dd12/code/open-eqa/evaluate-predictions.py", line 127, in <module>
Traceback (most recent call last):
  File "/home/hpc/v100dd/v100dd12/code/open-eqa/evaluate-predictions.py", line 127, in <module>
  File "/home/hpc/v100dd/v100dd12/code/open-eqa/openeqa/evaluation/llm_match.py", line 48, in get_llm_match_score
    set_openai_key(key=openai_key)
  File "/home/hpc/v100dd/v100dd12/code/open-eqa/openeqa/utils/openai_utils.py", line 17, in set_openai_key
    assert "OPENAI_API_KEY" in os.environ
AssertionError
  0%|          | 0/1636 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/hpc/v100dd/v100dd12/code/open-eqa/evaluate-predictions.py", line 127, in <module>
    main(parse_args())
  File "/home/hpc/v100dd/v100dd12/code/open-eqa/evaluate-predictions.py", line 109, in main
    main(parse_args())
  File "/home/hpc/v100dd/v100dd12/code/open-eqa/evaluate-predictions.py", line 109, in main
    score = get_llm_match_score(
  File "/home/hpc/v100dd/v100dd12/code/open-eqa/openeqa/evaluation/llm_match.py", line 68, in get_llm_match_score
    score = get_llm_match_score(
  File "/home/hpc/v100dd/v100dd12/code/open-eqa/openeqa/evaluation/llm_match.py", line 68, in get_llm_match_score
    main(parse_args())
  File "/home/hpc/v100dd/v100dd12/code/open-eqa/evaluate-predictions.py", line 109, in main
    raise e
  File "/home/hpc/v100dd/v100dd12/code/open-eqa/openeqa/evaluation/llm_match.py", line 48, in get_llm_match_score
    raise e
  File "/home/hpc/v100dd/v100dd12/code/open-eqa/openeqa/evaluation/llm_match.py", line 48, in get_llm_match_score
    score = get_llm_match_score(
  File "/home/hpc/v100dd/v100dd12/code/open-eqa/openeqa/evaluation/llm_match.py", line 68, in get_llm_match_score
    set_openai_key(key=openai_key)
  File "/home/hpc/v100dd/v100dd12/code/open-eqa/openeqa/utils/openai_utils.py", line 17, in set_openai_key
    set_openai_key(key=openai_key)
  File "/home/hpc/v100dd/v100dd12/code/open-eqa/openeqa/utils/openai_utils.py", line 17, in set_openai_key
    raise e
  File "/home/hpc/v100dd/v100dd12/code/open-eqa/openeqa/evaluation/llm_match.py", line 48, in get_llm_match_score
    assert "OPENAI_API_KEY" in os.environ
AssertionError
    assert "OPENAI_API_KEY" in os.environ
AssertionError
    set_openai_key(key=openai_key)
  File "/home/hpc/v100dd/v100dd12/code/open-eqa/openeqa/utils/openai_utils.py", line 17, in set_openai_key
    assert "OPENAI_API_KEY" in os.environ
AssertionError
[2025-01-27 05:41:21,855] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 3761251 closing signal SIGTERM
[2025-01-27 05:41:21,871] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 3761248) of binary: /home/hpc/v100dd/v100dd12/anaconda3/envs/openeqa/bin/python
Traceback (most recent call last):
  File "/home/hpc/v100dd/v100dd12/anaconda3/envs/openeqa/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/hpc/v100dd/v100dd12/anaconda3/envs/openeqa/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hpc/v100dd/v100dd12/anaconda3/envs/openeqa/lib/python3.9/site-packages/torch/distributed/run.py", line 816, in <module>
    main()
  File "/home/hpc/v100dd/v100dd12/anaconda3/envs/openeqa/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/hpc/v100dd/v100dd12/anaconda3/envs/openeqa/lib/python3.9/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/home/hpc/v100dd/v100dd12/anaconda3/envs/openeqa/lib/python3.9/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/hpc/v100dd/v100dd12/anaconda3/envs/openeqa/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/hpc/v100dd/v100dd12/anaconda3/envs/openeqa/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/hpc/v100dd/v100dd12/code/open-eqa/evaluate-predictions.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-01-27_05:41:21
  host      : a1622.nhr.fau.de
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3761249)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2025-01-27_05:41:21
  host      : a1622.nhr.fau.de
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 3761250)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-01-27_05:41:21
  host      : a1622.nhr.fau.de
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3761248)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
=== JOB_STATISTICS ===
=== current date     : Mon Jan 27 05:41:37 CET 2025
= Job-ID             : 2333500 on alex
= Job-Name           : Llama-2-70b-hf-eval
= Job-Command        : /home/hpc/v100dd/v100dd12/code/open-eqa/batch_script/batch_eval.sh
= Initial workdir    : /home/hpc/v100dd/v100dd12/code/open-eqa
= Queue/Partition    : a40
= Slurm account      : v100dd with QOS=normal
= Requested resources:  for 1-00:00:00
= Elapsed runtime    : 00:00:44
= Total RAM usage    : 0.3 GiB of assigned  GiB (%)
= Node list          : a1622
= Subm/Elig/Start/End: 2025-01-26T16:37:43 / 2025-01-26T16:37:43 / 2025-01-27T05:40:38 / 2025-01-27T05:41:22
======================
=== Quota infos ======
    Path              Used     SoftQ    HardQ    Gracetime  Filec    FileQ    FiHaQ    FileGrace    
    /home/hpc           99.3G   104.9G   209.7G        N/A     490K     500K   1,000K        N/A    
    /home/vault          0.0K  1048.6G  2097.2G        N/A       1      200K     400K        N/A    
======================
=== GPU utilization ==
gpu_name, gpu_bus_id, pid, gpu_utilization [%], mem_utilization [%], max_memory_usage [MiB], time [ms]
